/**
 * Discovers corpora/<id>/corpus.config.ts and:
 *   1. writes corpora/registry.generated.ts so the Next.js app can import
 *      every corpus statically (adding a corpus needs no code change);
 *   2. copies corpora/<id>/docs/* to public/corpora/<id>/ for PDF deep links.
 *
 * Runs automatically on postinstall, predev and prebuild.
 */
import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const corporaDir = path.join(root, 'corpora');
const publicDir = path.join(root, 'public', 'corpora');

const ids = fs
  .readdirSync(corporaDir, { withFileTypes: true })
  .filter((d) => d.isDirectory() && fs.existsSync(path.join(corporaDir, d.name, 'corpus.config.ts')))
  .map((d) => d.name)
  .sort();

if (ids.length === 0) {
  console.error('No corpora found (expected corpora/<id>/corpus.config.ts).');
  process.exit(1);
}

const registry = [
  '// AUTO-GENERATED by scripts/prepare-corpora.ts. Do not edit.',
  ...ids.map((id, i) => `import c${i} from './${id}/corpus.config';`),
  '',
  'export const corpora = {',
  ...ids.map((id, i) => `  ${JSON.stringify(id)}: c${i},`),
  '} as const;',
  '',
].join('\n');
fs.writeFileSync(path.join(corporaDir, 'registry.generated.ts'), registry);

fs.rmSync(publicDir, { recursive: true, force: true });
for (const id of ids) {
  const docs = path.join(corporaDir, id, 'docs');
  if (!fs.existsSync(docs)) continue;
  fs.cpSync(docs, path.join(publicDir, id), { recursive: true });
}

console.log(`prepare-corpora: ${ids.join(', ')}`);
